apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: hook-test
  namespace: argocd
spec:
  project: hook-test

  source:
    repoURL: https://github.com/beck3905/argocd-hook-test.git
    targetRevision: main
    path: chart

  destination:
    namespace: hook-test
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Prune=true
      - CreateNamespace=true
